INSERT INTO Creditos.CatalogoCreditos(IdCatalogo, Nombre, Valor, ValorPadre, Estado)
VALUES
(1, 'PRODUCTO', 0, NULL, 1),
(1, 'CREDITO DE CONSUMO', 1, NULL, 1),
(1, 'CREDITO HIPOTECARIO', 2, NULL, 1),
(1, 'CREDITO AUTOMOTRIZ', 3, NULL, 1),
(1, 'CREDITO COMERCIAL', 4, NULL, 1),
(1, 'CREDITO EDUCATIVO', 5, NULL, 1),
(1, 'CREDITO PRENDARIO', 6, NULL, 1),
(1, 'CREDITO MULTIDESTINO', 7, NULL, 1),


(2, 'SUBPRODUCTO', 0, NULL, 1),
(2, 'DIARIO', 1, NULL, 1),
(2, 'SEMANAL', 2, NULL, 1),
(2, 'QUINCENAL', 3, NULL, 1),
(2, 'SEMANAL', 4, NULL, 1),

(3, 'ESTADO DE CREDITO', 0, NULL, 1),
(3, 'SOLICITADO', 1, NULL, 1),
(3, 'EVALUACION', 2, NULL, 1),
(3, 'RECHAZADO', 3, NULL, 1),
(3, 'APROBADO', 4, NULL, 1),
(3, 'OBSERVADO', 5, NULL, 1),
(3, 'VENCIDO', 6, NULL, 1),
(3, 'DESEMBOLSADO', 7, NULL, 1),
(3, 'INCOBRABLE', 8, NULL, 1),
(3, 'PAGADO', 9, NULL, 1)